name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub to Hugging Face Hub
        uses: huggingface/hub-sync@v0.2.0
        with:
          github_repo_id: joberror/cognitoMM
          huggingface_repo_id: iamjoberror/bot-media
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: gradio
          private: false
